spring.application.name=MicroUsuarioSeguridad
server.port=8081

# Base de datos MySQL - XAMPP (sin password por defecto)
spring.datasource.url=jdbc:mysql://localhost:3306/db_ecomarket
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Basic Auth
spring.security.user.name=admin
spring.security.user.password=admin123

# Logs
logging.file.name=logs/ms-producto.log
logging.level.root=INFO
logging.level.com.example.MicroProducto=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html